# -*- coding: utf-8 -*-
import os
import sys
from typing import List, Dict

import numpy as np
import pandas as pd
import h5py
import matplotlib.pyplot as plt
import seaborn as sns

def set_plotting_style() -> None:
    sns.set(font="Arial")
    plt.rcParams["svg.fonttype"] = "none"
    style = sns.axes_style("white")
    style.update(sns.axes_style("ticks"))
    style["xtick.major.size"] = 2
    style["ytick.major.size"] = 2
    sns.set(font_scale=1.4, style=style)

def query_dis_per_gene(
    gene: str,
    distance_matrix: np.ndarray,
    gene_list: List[str],
    isoform2symbol: Dict[str, str],
    isoform2gene: Dict[str, str],
    gene_summary_df: pd.DataFrame
) -> pd.DataFrame:
    try:
        gene_idx = gene_list.index(gene)
    except ValueError:
        return pd.DataFrame()

    tmp_dis = pd.DataFrame(
        {"distance": distance_matrix[gene_idx, :], "gene_info": gene_list}
    )
    
    tmp_dis["gene_symbol"] = tmp_dis["gene_info"].map(isoform2symbol)
    tmp_dis["gene_id"] = tmp_dis["gene_info"].map(isoform2gene)
    
    tmp_dis = tmp_dis.merge(gene_summary_df, on="gene_info")
    
    return tmp_dis.sort_values("distance", ascending=True)

def main():
    set_plotting_style()
    
    # --- Configuration ---
    merged_info_path = "results/06_merged_data/merged_info_df.pkl"
    distance_matrix_path = "results/07_distance_matrix/merge_dis_complete.h5"
    output_dir = "results/downstream_analysis/15_isoform_neighbors"
    
    print("Loading data generated by the preprocessing pipeline...")
    if not all(os.path.exists(p) for p in [merged_info_path, distance_matrix_path]):
        print("Error: Missing required input files. Please ensure the Snakemake pipeline has run successfully.", file=sys.stderr)
        sys.exit(1)
        
    os.makedirs(output_dir, exist_ok=True)
    
    info_df = pd.read_pickle(merged_info_path)
    with h5py.File(distance_matrix_path, 'r') as f:
        distance_matrix = f['distance_matrix'][:]
    
    unique_isoforms = info_df.drop_duplicates('gene_info')
    isoform2symbol = pd.Series(unique_isoforms.gene_symbol.values, index=unique_isoforms.gene_info).to_dict()
    isoform2gene = pd.Series(unique_isoforms.gene_id.values, index=unique_isoforms.gene_info).to_dict()

    gene_summary = info_df.groupby('gene_info')['sample_info'].apply(list).reset_index()
    gene_summary["sample_num"] = gene_summary["sample_info"].apply(len)
    
    gene_list = info_df.gene_info.unique().tolist()
    filter_gene_list = [x for x in gene_list if "." in x]

    print(f"Analyzing neighbors for {len(filter_gene_list)} isoforms...")
    same_gene_transcript = []
    single_gene = []
    
    for gene in filter_gene_list:
        gene_dis_df = query_dis_per_gene(
            gene, distance_matrix, gene_list, isoform2symbol, isoform2gene, gene_summary
        )
        
        if gene_dis_df.empty:
            continue
            
        target_gene_symbol = gene_dis_df.iloc[0]["gene_symbol"]
        
        top_neighbors_symbols = gene_dis_df.iloc[1:6]["gene_symbol"].tolist()
        
        other_isoforms_symbols = gene_dis_df.iloc[1:]["gene_symbol"].tolist()
        
        if target_gene_symbol in top_neighbors_symbols:
            same_gene_transcript.append(gene)
        elif target_gene_symbol not in other_isoforms_symbols:
            single_gene.append(gene)
            
    total_isoforms = len(filter_gene_list)
    sole_transcript = len(single_gene)
    has_neighbors = len(same_gene_transcript)
    not_sole_transcript = total_isoforms - sole_transcript
    other_no_neighbors = not_sole_transcript - has_neighbors

    inner_labels = [f"Sole Transcript\n{sole_transcript:,}", f"Not Sole\n{not_sole_transcript:,}"]
    inner_sizes = [sole_transcript, not_sole_transcript]
    outer_labels = ["", f"Has Neighbors\n{has_neighbors:,}", f"No Neighbors\n{other_no_neighbors:,}"]
    outer_sizes = [sole_transcript, has_neighbors, other_no_neighbors]
    inner_colors = ["#a8dadc", "#f3855e"]
    outer_colors = ["#a8dadc", "#95b951", "#b19cd9"]

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.pie(
        outer_sizes, radius=1.0, labels=outer_labels, colors=outer_colors,
        wedgeprops=dict(width=0.3, edgecolor="w"), labeldistance=0.8,
        textprops=dict(color="black", size=11),
    )
    ax.pie(
        inner_sizes, radius=0.7, labels=inner_labels, colors=inner_colors,
        wedgeprops=dict(width=0.4, edgecolor="w"), labeldistance=0.55,
        textprops=dict(color="black", size=11, weight="bold"),
    )

    ax.set(aspect="equal")
    output_path = os.path.join(output_dir, "isoform_neighbor_sunburst_plot.png")
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"\nAnalysis complete. Plot saved to {output_path}")

if __name__ == "__main__":
    main()